### ISSUE TITLE
I installed all the modules and stuff and it says no modules found

### ISSUE THREAD

**Issue by Tumble7** [NuclearLighthouseStudios/Cassette-Video-Encoder#2]
i installed everything and im running python 3 but it cannot detect numpy, pillow/PIL, scipy, and soundfile. it says no module named numpy and stuff like that. i am running python 3.9 and i have 3.7 and 3.6. i dont know what to do, i have not used python a lot because its very annoying to have to download all these modules to get one program to work. do you know what I should do to fix this? im lost here.

**Comment by Tumble7** [comment]
heres the error i got btw: Traceback (most recent call last):
  File "C:\Users\garre\Downloads\Cassette-Video-Encoder-master\Cassette-Video-Encoder-master\enc.py", line 7, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

**Comment by NuclearLighthouseStudios** [comment]
Are you running the script in a virtualenv? And how did you install the packages?

**Comment by NuclearLighthouseStudios** [comment]
First you said:
> i installed everything

But then:
> i tried to install the packages but the installer gave an error

So, did you install the packages or not? If they're not installed it would make sense for python to say it can't find them.

I've gone through the requirements and updated all of them to the latest version available, so please try installing them again.

**Comment by Tumble7** [comment]
ok ill try it, thanks

**Comment by Tumble7** [comment]
ok now everything installed but when i open the enc program, it closes, but before it closes, it says something like USAGE: enc.py but only for 1/8 of a second and then it closes the window i installed everything and it said it all installed i double checked. im sorry for bothering you btw, but i hope this info helps.

**Comment by Tumble7** [comment]
it says `enc.py: error: the following arguements are required: -i/input,outfile`

**Comment by NuclearLighthouseStudios** [comment]
Yeah, it's a command line application. You're gonna have to run in from the command line and specify the parameters like I've explained in the readme file.

**Comment by Tumble7** [comment]
ok ill try it, sorry if im wasting ur time

**Comment by Tumble7** [comment]
i got it to work and generate an intro.wav file, one last thing though, there is no intro folder in my pc, do i make a directory in python called intro?

**Comment by Tumble7** [comment]
oop, i got it to work, one more thing though. can you do videos/gifs? if so how do you encode that format?

**Comment by Tumble7** [comment]
well all works except the decoder anyway, it only asks for my microphone and shows a black screen on chrome when i try to decode the image

**Comment by NuclearLighthouseStudios** [comment]
> can you do videos/gifs?

Sure. You need to split up the video into an image sequence with ffmpeg or some other tool, then encode them like explained in the readme file.

As for the decoder, how are you playing the file? If chrome is recording from the microphone or line input of your computer then you'll have to play it into that from a second device or connect the output of your computer back to the input somehow.

On my computer I can tell the browser to record the output sound of my computer, but I don't know if that's an option on windows.

**Comment by Tumble7** [comment]
ok, thanks for the advice! im glad i got everything working. have a good day :)
